---
- name: Run bench/bin/gen-initial-dataset
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/bench
  command: |
    bin/gen-initial-dataset

- name: Run db/init.sh
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb
  command: |
    db/init.sh

- name: Install cpanm for torb.perl
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/torb/webapp/perl
  shell:
    bash -lc "cpanm --installdeps --force ."

- name: Restart and enable mariadb
  become: yes
  become_user: root
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart and enable h2o
  become: yes
  become_user: root
  systemd:
    name: h2o
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: systemd restart torb.perl
  become: yes
  become_user: root
  systemd:
    name: torb.perl
    state: restarted
    daemon_reload: yes
    enabled: yes
