---
- name: deploy torb/bench binary
  become: yes
  become_user: isucon
  copy:
    src: ../../../../torb/bench/bin.Linux.x86_64/bench
    dest: /home/isucon/torb/bench/bin/bench
    owner: isucon
    group: isucon
    mode: u=rwX,g=rX,o=rX
