---
- name: deploy torb (without bench)
  become: yes
  become_user: isucon
  synchronize:
    src: ../../../../
    dest: /home/isucon/torb
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.gitignore"
      - "--exclude=bench"
      - "--exclude=provisioning"

- name: chown torb
  become: yes
  become_user: root
  file:
    dest: /home/isucon/torb
    owner: isucon
    group: isucon
    mode: u=rwX,g=rX,o=rX
    recurse: yes
