---
- name: iptables open tcp 80 port
  become: yes
  become_user: root
  iptables:
    flush: true
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT

- name: Put h2o.conf
  become: yes
  become_user: root
  copy:
    src: h2o.conf
    dest: /etc/h2o/h2o.conf

- name: Put php-h2o.conf
  become: yes
  become_user: root
  copy:
    src: php-h2o.conf
    dest: /etc/h2o/php-h2o.conf

- name: Put torb.perl.service
  become: yes
  become_user: root
  blockinfile:
    create: yes
    src: torb.perl.service
    dest: /etc/systemd/system/torb.perl.service

- name: Put torb.php.service
  become: yes
  become_user: root
  blockinfile:
    create: yes
    src: torb.php.service
    dest: /etc/systemd/system/torb.php.service
