---
- name: Install Go 1.10.3
  become: yes
  become_user: isucon
  command: |
    /home/isucon/xbuild/go-install 1.10.3 /home/isucon/local/go

- name: Add PATH for Go
  become: yes
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    dest: /home/isucon/.bash_profile
    content: |
      export PATH=/home/isucon/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/home/isucon/local/go
